### ISSUE TITLE
Public blacklist

### ISSUE THREAD

**Issue by seasox** [jflessau/winbot-twitter-bot#1]
Hi there! Are there any public blacklists for winbot available? I currently use the following, started tweeting yesterday:

```
BotSp0tterBot
RealBotSp0tter
bottybotbot1
RealB0tSpotter
```

**Comment by jflessau** [comment]
Hi seasox! 
I've added my list to the new folder _filled-blacklist_
Works quite well so far, but some new BotSpotters appear every now and then.

**Comment by mikes1980** [comment]
Hi, how do you go about blocking people on the blacklist?  Is there another bot you use for this?  If so, what's it called?
