### ISSUE TITLE
create_friendship

### ISSUE THREAD

**Issue by Latlanh** [jflessau/winbot-twitter-bot#12]
Hi thx for your work and sorry for my bad english.
I use your work since 2 day and sometimes twitter.create_friendship doesn't work...
Did you know why?

**Comment by jflessau** [comment]
Hi Latlanh, 
there are two main reasons for this:
- those users blocked you
- in the time between getting the tweets and users to follow and actually following them, these accounts already disappeared

Greetings from germany :)
– Jan
