### ISSUE TITLE
Follower

### ISSUE THREAD

**Issue by OneAlex01** [jflessau/winbot-twitter-bot#15]
Is the bot following every person by retweeting a tweet? Would be good having an option not to follow a person if the giveaway tweets contains not the word "follow" because there are giveaways where you only have to rt a tweet.

**Comment by jflessau** [comment]
Good point. This could really save a lot of time. I will implement it as soon as possible. Thanks for the input!

**Comment by jflessau** [comment]
Bot now checks for the word `follow` before it will follow the author of a giveaway:
```python
        if (tweet_has_string(tweet, 'follow')):
            follow_author(tweet)
```
