### ISSUE TITLE
search query problem

### ISSUE THREAD

**Issue by sa-ba01** [jflessau/winbot-twitter-bot#18]
Hello,

I wanted to add German words to the search query. I added them with an OR to rt2win and retweet to win, but I found out that the winbot search only for the first words, so rt2win, not the German words. 
How can I fix this problem, so the winbot is mixing the search query words?

**Comment by jflessau** [comment]
Hi there!
From twitters [docs](https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets.html):

> A UTF-8, URL-encoded search query of 500 characters maximum, including operators. Queries may additionally be limited by complexity.

The last sentence is key: I guess they don’t want you to use a lot of operators.
