### ISSUE TITLE
Can't launch the script from another directory

### ISSUE THREAD

**Issue by Jorlejeu** [jflessau/winbot-twitter-bot#19]
Hey !
First of all, thank you for the script. There is just one thing : I don't really understand how the search_query works, has I use very specific words in French and the bot isn't able to find the tweets, even though I'm manually finding them. If you could just explain it a bit in the documentation, it would be great ! (Very nice doc by the way!)

I've got a small problem with the script : when I launch it from another directory (for example : `python winbot-twitter-bot/winbot.py` ), the script can"t find the _blacklisted-users.txt_ file :-( (here's the full
error : 
```
Traceback (most recent call last):
  File "winbot-twitter-bot/winbot.py", line 290, in <module>
    win_things()
  File "winbot-twitter-bot/winbot.py", line 31, in win_things
    filtered_tweets = filter_tweets(fresh_tweets)
  File "winbot-twitter-bot/winbot.py", line 63, in filter_tweets
    tweets = blacklisted_users_filter(tweets)
  File "winbot-twitter-bot/winbot.py", line 70, in blacklisted_users_filter
    blacklisted_users = get_list("blacklisted-users.txt")
  File "winbot-twitter-bot/winbot.py", line 40, in get_list
    file = open(filename, "r")
IOError: [Errno 2] No such file or directory: 'blacklisted-users.txt'
```

That's odd because I wanted to set the bot on my Debian Server and schedule it with Cron, but I can't since the script can't be launched from another directory.

Do you know where it comes from ?

Thank you for your help !

**Comment by jflessau** [comment]
Hi Jorlejeu, 
lauch it after you switched into the directory: 

``` batch
cd /path/to/bots/dir/ && python winbot.py
```

Because files like the blacklist are fetched by their relative path, you can’t simply run the bot from every directory without switching to the bots directory. 

Edit: Searching with a query through twitters API is a bit diffrent from searching with the search on their website. I couldn’t figure out why this is the case, though.

**Comment by Jorlejeu** [comment]
Hey JFlessau,

Thank you for your answer. I'll simply create a shell script inside winbot directory and make a cron launch the script.

For the search query, I'll have a look at Twitter's API Documentation.

Cheers !
