### ISSUE TITLE
update broke the app

### ISSUE THREAD

**Issue by Darkcast** [jflessau/winbot-twitter-bot#4]
after the recent update when I execute the application I the the following sceen and they it ends

------------------------------------------------------------
--------------------------WinBot----------------------------
************************************************************
SETTINGS:
Search for 20 tweets in each cycle
amount of cycles: 2
sleeps for 180 seconds
whenever bot interacted 4 times with twitter-api
follows max. 3 users, who were mentioned in a tweet
------------------------------------------------------------
Errors/Warnings:

**Comment by jflessau** [comment]
'Errors/Warnings:' is the last thing it prints to terminal before starting to retweet. If there are no errors or warnings, you won't see anything else until it's completely done (wich can take a few hours - depending in the settings). 
Start it, let it run some time and watch the attatched twitter account. 

When completely done done, the bot prints a final message including the string 'DONE'.
