### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by chatzipavlou** [jflessau/winbot-twitter-bot#8]
File "winbot.py", line 30
    print '\n\n\nstart cycle:' +str(i + 1)
                             ^
SyntaxError: invalid syntax

**Comment by jflessau** [comment]
I’ve replaced every single quote (') in winbot.py with double quotes ("), that should fix it. 
Also: Do not run this script by using pythoin IDE. 

Edit: Changet the print statements to fit python 3 syntax.
